### ISSUE TITLE
File-related output memory growth on k8s

### ISSUE THREAD

**Issue by mstemm** [draios/falco#338]
Reported on public slack:

Hi, I am running Falco in a container on K8 and I am having issues with container memory going up all the time (15-20MBs per hour)

I have configured Falco with custom rules to generate events for every process start and outgoing connect syscalls (I have some snet CIDRs whitelisted) - so I have Falco to log quite a lot of output messages.

When I inspect Falco process from the host - I do not see the memory going up, but Kubernetes or 'docker stats <falco container>' shows memory going up all the time (edited)

This only happens when I log events to a file. If I disable file output and enable output to stdout the issue goes away. The directory where Falco logs are going is mapped to a directory on the host

Rate of events is quite high - file grows about 20-30MB per hour. When I replace my custom rules with default ones - which do not generate events under normal K8 node activities - then the issue goes away even if Falco is logging to file. So there is a clear correlation with the volume of events logged.

Again, inspecting Falco process on the host with 'htop' does not show any noticeable sign of memory increase, but container memory goes up pretty quickly.

Falco v0.9.0, and I have build a docker container locally using Dockerfile from Falco repo.

**Comment by alukyan** [comment]
I posted the rule file I used to the slack channel

**Comment by mstemm** [comment]
[falco_rules.global.yaml.txt](https://github.com/draios/falco/files/1839580/falco_rules.global.yaml.txt)

**Comment by mstemm** [comment]
I'm trying to reproduce this now, but no luck so far. Some additional questions:

* did you have keep_alive on for the file-based output?
* I'm assuming you have json_output=true?

If you'd like to attach your falco.yaml config, that would help also.

**Comment by mstemm** [comment]
Also, did you change the throttling parameters at all?

**Comment by mstemm** [comment]
Here's what I've tried so far:

 * Run falco via docker version "Docker version 18.02.0-ce, build fc4de44" using: `docker run --rm -i -t --name falco --privileged -v /tmp/events.txt:/host/tmp/events.txt -v falco_rules.yaml:/etc/falco/falco_rules.yaml -v falco.yaml:/etc/falco/falco.yaml -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/falco`
 * Here's the contents of falco.yaml: [falco.yaml.txt](https://github.com/draios/falco/files/1857542/falco.yaml.txt)
 * falco_rules.yaml is the normal set of rules from the development branch, plus the following rule:

```
- rule: an open was seen
  desc: foo
  condition: evt.type in (open, connect, accept, execve, clone, fork)
  output: An open was seen (command=%proc.cmdline connection=%fd.name)
  priority: INFO
```

Obviously this rule triggers on lots of events. On my test environment, `/tmp/events.txt` is growing by ~1MB/second.

* Running `docker stats falco` and watching the `MEM USAGE` column
* Running `top` and watching the resident size

After 30minutes, MEM USAGE is pretty steady at ~16.8MB and resident size is pretty steady at ~20600kb:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
dc786b796248        falco               23.46%              16.89MiB / 7.79GiB   0.21%               370B / 0B           0B / 2.8MB          1
```

```
3923 root      20   0   82976  20684   7716 R  41.4  0.3   3:02.48 falco
```
I'll try specifically running falco as a k8s daemonset next, *without* connecting falco to the k8s api server.

**Comment by alukyan** [comment]
Falco is running in standalone mode (not connected to K8 api server).
I attached the config file

[falco.yaml.txt](https://github.com/draios/falco/files/1857883/falco.yaml.txt)

**Comment by alukyan** [comment]
For file settings I see that difference is `keep_alive` for my settings is `false` and in your case it is `true`. We use `keep_alive = false` so that log rotation works correctly and Falco does not keep writing to opened file that was renamed.

One of my team members suggested trying to disable `buffered_outputs` to see if this helps. I am going to try this right now

**Comment by alukyan** [comment]
Just verified on my cluster that none of `buffered_outputs` or `keep_alive` have any impact on container memory growth in K8. When file output is enabled even with `buffered_outputs=false` or `keep_alive=true` container memory slowly keeps growing

```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
4ba44eda4d66        55.20%              31.72 MiB / 3.339 GiB   0.93%               0 B / 0 B           0 B / 958 kB        1
```

5 minutes later it is

```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
4ba44eda4d66        29.58%              36.46 MiB / 3.339 GiB   1.07%               0 B / 0 B           0 B / 958 kB        1```

Htop does not show memory leak:

```
35289 root       20   0  201M  2936  2500 S  0.0  0.1  0:00.00 │     ├─ docker-containerd-shim 4ba44eda4d66004537d69679728419271b04318fae8b340b3fb88f0f4e464301 /var/run/docker/libcontainerd/4ba44eda4d66004537d6967972
 35305 root       20   0 58900 13264  7832 S  1.9  0.4  0:09.86 │     │  └─ falco
```

**Comment by alukyan** [comment]
Kubernetes node data:

```
Kernel Version:
4.13.0-1007-azure
OS Image: Debian GNU/Linux 9 (stretch)
Container Runtime Version: docker://1.13.1
Kubelet Version: v1.9.2
Kube-Proxy Version: v1.9.2
Operating system: linux
Architecture: amd64
```

**Comment by alukyan** [comment]
I did some more investigation and it seem like the container memory increase is caused by OS caching when Falco writes output to log files.

I exec'ed into the container and observed that container memory growth correlates with `Cached` memory value increase in `/proc/meminfo`. It looks there is a way to ask kernel to free cached memory buffers by doing this

```
echo 3 > /proc/sys/vm/drop_caches
```

I exec'ed into one of 3 Falco daemonsets, run the above command and indeed the container memory got reset to about 13MB. See the memory drop on the screenshot from K8 dashboard below.

![memory](https://user-images.githubusercontent.com/8131002/38116116-99613f54-3363-11e8-9a34-a5d654b30316.jpg)

So I guess this can be addressed by setting reasonable memory limit on Falco container and let Linux to free cached memory automatically when it runs out of available memory.

I will validate this and update the thread with results

**Comment by mstemm** [comment]
Great, thanks for the extra investigation. Also looks related: https://github.com/kubernetes/kubernetes/issues/43916.

**Comment by alukyan** [comment]
I have validated approach with setting a memory limit on Falco container on K8 (160Mi). Falco container memory reaches maximum limit and stays there. 
Falco process itself uses much less memory than 160Mi - around 15-20 MB, but setting maximum memory to 80Mi has blocked Falco container from starting - kernel module is being compiled upon start and it requires at least 100Mi.

I think this issue can be closed now, but it would be great to update Falco wiki with some guidance for Kubernetes so people don't freak out because of continuous memory growth and apply memory limits on Falco container.

**Comment by mstemm** [comment]
Ok, I added a note to the wiki here: https://github.com/draios/falco/wiki/How-to-Install-Falco-using-Containers-and-or-Orchestration#additional-notes-on-running-falco-in-containersk8s. I'll close this issue for now. Thanks for the investigation!

**Comment by remster** [comment]
@mstemm we seem to have a similar problem and are looking for workarounds. What do you mean by: "memory limit on Falco container on K8 (160Mi)."? I don't pressume this is `resources.limits` because I interpret these cause the pod's eviction with OOMKilled - which is not exactly the objective.

**Comment by mstemm** [comment]
I'm guessing a bit, as it was @alukyan who came up with the original workaround. It sounds like the limit to change is `memory.available`.

**Comment by alukyan** [comment]
Here is a Falco related fragment of K8s daemonset manifest that worked for me
```
containers:
      - name: falco
        image: griffink8test.azurecr.io/gcp/falco:0.9.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "160Mi"
          requests:
            memory: "100Mi"
            cpu: "100m"
```
