### ISSUE TITLE
IN operators may not work with fd.snet + netmasks

### ISSUE THREAD

**Issue by mstemm** [draios/falco#339]
In falco, `... in (a, b, c, ...)`expressions are implemented as a set membership test. However, when the expression is something like `fd.snet`, where you want to compare against a netmask, it's actually better to break up the IN into a series of OR + equals.

**Comment by alukyan** [comment]
From supportability perspective supporting IN for netmasks is way more manageable because rules will be written in terms of lists that can be appended by local rules. For Host IDS solutions it makes possible to define global whitelists for hosts to ignore and append environment specific netmasks for each deployment in local rules.
