### ISSUE TITLE
Json output doesnt follow output field syntax

### ISSUE THREAD

**Issue by Fsero** [draios/falco#82]
Hi,

if in falco config i select the json output as true, the real json output doesnt include the priority or the description. Lets give an example:

- rule: ssh_incoming_connections
  desc: ips connected to ssh server
  condition: ssh_port and inbound
  output: "sshd incoming connection (connection=%fd.name)"
  priority: WARNING

this is rendered as

`{"fd.name":"2.2.2.2:60310->1.1.1.1:22"}
`
if i disable the json output the output gives much much more info

`May 22 16:13:38 test02 falco: sshd incoming connection (connection=2.2.2.2:60502->1.1.1.1:22)`

is intended behaviour? is there any way to affect json output?

Thanks in advance i really do love falco :)

**Comment by mstemm** [comment]
This behavior stems from using the underlying sysdig libraries to handle event formatting. When using json format, the fields from the format string are retrieved and an object is created with the values of all those fields. Here's an example of sysdig with json output:

```
sudo sysdig -j -n 10 -p "The process name is %proc.name"
[{"proc.name":"sysdig"},
{"proc.name":"as"},
{"proc.name":"as"},
{"proc.name":"as"},
{"proc.name":"sysdig"},
{"proc.name":"as"},
{"proc.name":"as"},
{"proc.name":"as"},
{"proc.name":"as"}]
```

So that explains the current behavior.

However, you'e right that this output is pretty limited. Overall fixing this seems reasonable. We'd probably want to use a mix of the non-json and json output formats available in sysdig and build on that with the rule name and priority to create a json object per event.
